# Generated by Django 3.2.18 on 2023-05-16 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='priorities',
            field=models.ManyToManyField(related_name='post_priorities', to=settings.AUTH_USER_MODEL),
        ),
    ]
