# Generated by Django 3.2.18 on 2023-05-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='address_detail',
        ),
    ]
