# Generated by Django 3.2.18 on 2023-05-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_address_user_address_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_extra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_postcode',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
