# Generated by Django 3.2.18 on 2023-05-17 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
