# Generated by Django 3.2.18 on 2023-05-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='extra_address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
