# Generated by Django 3.2.18 on 2023-05-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20230515_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='location',
        ),
    ]
