# Generated by Django 3.2.18 on 2023-05-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20230512_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateField(),
        ),
    ]
